### ISSUE TITLE
Allow to change "Dear gamers," text

### ISSUE THREAD

**Issue by MasterGroosha** [foone/Cyberpunk2077Apology#2]
In the current version, you cannot change "Dear gamers," text, which looks bad if you use language other than English ([Russian, for example](https://twitter.com/CDPR_RU/status/1338390812728696832)).

Since CDPR doesn't always use these "intro words", I think extra input field isn't required, just basic Markdown support.

Thanks in advance!

**Comment by foone** [comment]
I'm looking into this. It's a separate font, but I think it's using the Blender Bold that the cyberpunk.net site uses, so I'll see if that matches close enough.

**Comment by foone** [comment]
Fixed, using commit 164276137586a9e10759faf309cdfbef97861691.
Thanks!
